import { Sound, SoundRights, LicenseScope, AppMode } from '../types';

// ─────────────────────────────────────────────────────────────────────────────
// Single source of truth for license/rights derivation, export checks, and
// badge presentation. No React / UI imports here — pure logic.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Procedural sounds (Tone.js synths, including Claude- or keyword-generated
 * presets) are synthesized locally from parameters, so the user owns the audio
 * outright. Safe in every mode.
 */
export function deriveProceduralRights(prompt?: string, provider = 'Tone.js (procedural)'): SoundRights {
  return {
    source: 'tone_synth',
    provider,
    prompt,
    licenseScope: 'commercial_org',
    attributionRequired: false,
    canModify: true,
    canExport: true,
    canUseInClientWork: true,
    generatedAt: Date.now(),
  };
}

/**
 * Audio generated by a hosted AI API (ElevenLabs, Stability, …). The usable
 * scope depends on the plan that was active at generation time. When the plan
 * is a known commercial tier we mark it commercial; otherwise we stay
 * conservative (personal / unknown) so commercial exports get flagged.
 */
export function deriveAiApiRights(opts: {
  provider: string;
  model?: string;
  prompt?: string;
  plan?: string; // 'commercial' | 'personal' | undefined
  termsUrl?: string;
}): SoundRights {
  const plan = (opts.plan ?? '').toLowerCase();
  const isCommercial = plan === 'commercial' || plan === 'business' || plan === 'pro';
  const scope: LicenseScope = isCommercial
    ? 'commercial_individual'
    : plan === 'personal'
      ? 'personal'
      : 'unknown';
  return {
    source: 'ai_api',
    provider: opts.provider,
    model: opts.model,
    prompt: opts.prompt,
    planAtGeneration: opts.plan,
    licenseScope: scope,
    attributionRequired: false,
    canModify: true,
    canExport: true,
    canUseInClientWork: isCommercial,
    termsUrl: opts.termsUrl,
    generatedAt: Date.now(),
  };
}

/** User-uploaded / imported audio: rights are unknown until the user clarifies. */
export function deriveUploadRights(): SoundRights {
  return {
    source: 'user_upload',
    provider: 'User',
    licenseScope: 'unknown',
    attributionRequired: false,
    canModify: true,
    canExport: true,
    canUseInClientWork: false,
    generatedAt: Date.now(),
  };
}

/**
 * Infer rights for a legacy sound that predates the rights system, using its
 * existing tags. Seeds / AI presets / editor-made sounds are all procedural
 * (owned); imported sounds are uploads (unknown).
 */
export function backfillRights(sound: Sound): SoundRights {
  const tags = sound.tags ?? [];
  if (sound.id.startsWith('import-') || tags.includes('imported') || tags.includes('recorded')) {
    return deriveUploadRights();
  }
  // seed / ai / editor-created → procedural presets, owned by the user
  const provider = tags.includes('ai') ? 'Claude (procedural)' : 'Tone.js (procedural)';
  const rights = deriveProceduralRights(undefined, provider);
  rights.generatedAt = sound.createdAt ?? Date.now();
  return rights;
}

/** Ensure a sound has rights, backfilling if missing. Returns the sound unchanged when already present. */
export function withRights(sound: Sound): Sound {
  if (sound.rights) return sound;
  return { ...sound, rights: backfillRights(sound) };
}

// ─────────────────────────────────────────────────────────────────────────────
// Export gating
// ─────────────────────────────────────────────────────────────────────────────

const COMMERCIAL_OK: LicenseScope[] = ['commercial_individual', 'commercial_org'];

/**
 * Whether a sound's rights permit export in the active mode.
 * - personal & research modes: anything goes (they're non-commercial workspaces).
 * - commercial mode: only sounds with a commercial license scope pass cleanly.
 */
export function rightsAllowExport(rights: SoundRights | undefined, mode: AppMode): { ok: boolean; reason?: string } {
  const r = rights;
  if (!r) {
    return mode === 'commercial'
      ? { ok: false, reason: 'No rights metadata — provenance unknown.' }
      : { ok: true };
  }
  if (r.canExport === false) {
    return { ok: false, reason: 'Marked as not exportable.' };
  }
  if (mode !== 'commercial') return { ok: true };

  if (COMMERCIAL_OK.includes(r.licenseScope)) return { ok: true };

  const labels: Record<LicenseScope, string> = {
    personal: 'Personal-use only',
    commercial_individual: 'Commercial OK',
    commercial_org: 'Commercial OK',
    research_only: 'Research only — not cleared for commercial use',
    unknown: 'Unknown rights — not verified for commercial use',
  };
  return { ok: false, reason: labels[r.licenseScope] ?? 'Not cleared for commercial use.' };
}

export interface ExportOffender {
  sound: Sound;
  reason: string;
}

/** Check a batch of sounds for export in the active mode; returns the offenders. */
export function checkExportRights(sounds: Sound[], mode: AppMode): { offenders: ExportOffender[] } {
  const offenders: ExportOffender[] = [];
  for (const sound of sounds) {
    const { ok, reason } = rightsAllowExport(sound.rights, mode);
    if (!ok) offenders.push({ sound, reason: reason ?? 'Not cleared for export.' });
  }
  return { offenders };
}

// ─────────────────────────────────────────────────────────────────────────────
// Badge presentation
// ─────────────────────────────────────────────────────────────────────────────

export interface RightsBadge {
  label: string;
  emoji: string;
  className: string;
  title: string;
}

export function rightsBadge(rights: SoundRights | undefined): RightsBadge {
  const scope = rights?.licenseScope ?? 'unknown';
  const provider = rights?.provider ? ` · ${rights.provider}` : '';
  switch (scope) {
    case 'commercial_individual':
    case 'commercial_org':
      return {
        label: 'Commercial OK',
        emoji: '✅',
        className: 'text-emerald-400 border-emerald-700/60 bg-emerald-900/30',
        title: `Cleared for commercial use${provider}`,
      };
    case 'personal':
      return {
        label: 'Personal',
        emoji: '🏠',
        className: 'text-sky-300 border-sky-700/60 bg-sky-900/30',
        title: `Personal-use only${provider}`,
      };
    case 'research_only':
      return {
        label: 'Research',
        emoji: '🧪',
        className: 'text-amber-300 border-amber-700/60 bg-amber-900/30',
        title: `Experimental / research only — verify rights before commercial use${provider}`,
      };
    case 'unknown':
    default:
      return {
        label: 'Unknown',
        emoji: '❓',
        className: 'text-gray-400 border-gray-600/60 bg-gray-800/50',
        title: `Rights unknown — not verified${provider}`,
      };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Mode metadata (used by the header selector)
// ─────────────────────────────────────────────────────────────────────────────

export const MODE_INFO: Record<AppMode, { label: string; emoji: string; blurb: string }> = {
  personal: {
    label: 'Personal Lab',
    emoji: '🏠',
    blurb: 'Experiments, demos & learning. All sources allowed; sounds tagged for personal use.',
  },
  commercial: {
    label: 'Commercial-Safe',
    emoji: '💼',
    blurb: 'Business, client & product use. Exports warn when a sound has uncertain rights.',
  },
  research: {
    label: 'Experimental',
    emoji: '🧪',
    blurb: 'Prototype freely. Outputs labeled research-only — verify rights before commercial use.',
  },
};
